[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/v8/finance/*"
  to = "https://query1.finance.yahoo.com/v8/finance/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
